// src/utils/countryNames.js
// Normaliza los nombres de país que devuelve el mapa (en inglés,
// ej. "Spain", "United States", "Republic of Korea") a las claves de región
// usadas en regionData.js (en español, ej. "España", "Estados Unidos", "Corea").
const COUNTRY_NAME_TO_REGION = {
  spain: 'España',
  france: 'Francia',
  'united states': 'Estados Unidos',
  'united states of america': 'Estados Unidos',
  usa: 'Estados Unidos',
  russia: 'Rusia',
  italy: 'Italia',
  mexico: 'México',
  argentina: 'Argentina',
  chile: 'Chile',
  germany: 'Alemania',
  'united kingdom': 'Inglaterra',
  england: 'Inglaterra',
  'republic of korea': 'Corea',
  'south korea': 'Corea',
  colombia: 'Colombia',
  bolivia: 'Bolivia',
  japan: 'Japón',
  syria: 'Siria',
  nigeria: 'Nigeria',
  // Países añadidos en la importación de 2026-08-19 (historia-anarquista)
  armenia: 'Armenia',
  brazil: 'Brasil',
  china: 'China',
  cuba: 'Cuba',
  egypt: 'Egipto',
  greece: 'Grecia',
  macedonia: 'Macedonia',
  paraguay: 'Paraguay',
  peru: 'Perú',
  poland: 'Polonia',
  ukraine: 'Ucrania',
  uruguay: 'Uruguay'
};

// Diccionario inglés → español de los 174 países del mapa (propiedades N del GeoJSON).
// Se usa para el tooltip del mapa y el efecto hover.
const COUNTRY_EN_TO_ES = {
  Afghanistan: 'Afganistán',
  Albania: 'Albania',
  Algeria: 'Argelia',
  Angola: 'Angola',
  Argentina: 'Argentina',
  Armenia: 'Armenia',
  Australia: 'Australia',
  Austria: 'Austria',
  Azerbaijan: 'Azerbaiyán',
  Bahamas: 'Bahamas',
  Bangladesh: 'Bangladés',
  Belarus: 'Bielorrusia',
  Belgium: 'Bélgica',
  Belize: 'Belice',
  Benin: 'Benín',
  Bhutan: 'Bután',
  Bolivia: 'Bolivia',
  'Bosnia and Herzegovina': 'Bosnia y Herzegovina',
  Botswana: 'Botsuana',
  Brazil: 'Brasil',
  'Brunei Darussalam': 'Brunéi',
  Bulgaria: 'Bulgaria',
  'Burkina Faso': 'Burkina Faso',
  Burundi: 'Burundi',
  Cambodia: 'Camboya',
  Cameroon: 'Camerún',
  Canada: 'Canadá',
  'Central African Republic': 'República Centroafricana',
  Chad: 'Chad',
  Chile: 'Chile',
  China: 'China',
  Colombia: 'Colombia',
  'Costa Rica': 'Costa Rica',
  Croatia: 'Croacia',
  Cuba: 'Cuba',
  Cyprus: 'Chipre',
  'Czech Republic': 'República Checa',
  "Côted'Ivoire": 'Costa de Marfil',
  'Dem. Rep. Korea': 'Corea del Norte',
  'Democratic Republic of the Congo': 'República Democrática del Congo',
  Denmark: 'Dinamarca',
  Djibouti: 'Yibuti',
  'Dominican Republic': 'República Dominicana',
  Ecuador: 'Ecuador',
  Egypt: 'Egipto',
  'El Salvador': 'El Salvador',
  'Equatorial Guinea': 'Guinea Ecuatorial',
  Eritrea: 'Eritrea',
  Estonia: 'Estonia',
  Eswatini: 'Esuatini',
  Ethiopia: 'Etiopía',
  'Falkland Islands': 'Islas Malvinas',
  Fiji: 'Fiyi',
  Finland: 'Finlandia',
  France: 'Francia',
  Gabon: 'Gabón',
  Georgia: 'Georgia',
  Germany: 'Alemania',
  Ghana: 'Ghana',
  Greece: 'Grecia',
  Greenland: 'Groenlandia',
  Guatemala: 'Guatemala',
  Guinea: 'Guinea',
  'Guinea-Bissau': 'Guinea-Bisáu',
  Guyana: 'Guyana',
  Haiti: 'Haití',
  Honduras: 'Honduras',
  Hungary: 'Hungría',
  Iceland: 'Islandia',
  India: 'India',
  Indonesia: 'Indonesia',
  Iran: 'Irán',
  Iraq: 'Irak',
  Ireland: 'Irlanda',
  Italy: 'Italia',
  Jamaica: 'Jamaica',
  Japan: 'Japón',
  Jordan: 'Jordania',
  Kazakhstan: 'Kazajistán',
  Kenya: 'Kenia',
  Kosovo: 'Kosovo',
  Kuwait: 'Kuwait',
  Kyrgyzstan: 'Kirguistán',
  'Lao PDR': 'Laos',
  Latvia: 'Letonia',
  Lebanon: 'Líbano',
  Lesotho: 'Lesoto',
  Liberia: 'Liberia',
  Libya: 'Libia',
  Lithuania: 'Lituania',
  Luxembourg: 'Luxemburgo',
  Macedonia: 'Macedonia',
  Madagascar: 'Madagascar',
  Malawi: 'Malaui',
  Malaysia: 'Malasia',
  Mali: 'Malí',
  Mauritania: 'Mauritania',
  Mexico: 'México',
  Moldova: 'Moldavia',
  Mongolia: 'Mongolia',
  Montenegro: 'Montenegro',
  Morocco: 'Marruecos',
  Mozambique: 'Mozambique',
  Myanmar: 'Birmania',
  Namibia: 'Namibia',
  Nepal: 'Nepal',
  Netherlands: 'Países Bajos',
  'New Caledonia': 'Nueva Caledonia',
  'New Zealand': 'Nueva Zelanda',
  Nicaragua: 'Nicaragua',
  Niger: 'Níger',
  Nigeria: 'Nigeria',
  'Northern Cyprus': 'Chipre del Norte',
  Norway: 'Noruega',
  Oman: 'Omán',
  Pakistan: 'Pakistán',
  Palestine: 'Palestina',
  Panama: 'Panamá',
  'Papua New Guinea': 'Papúa Nueva Guinea',
  Paraguay: 'Paraguay',
  Peru: 'Perú',
  Philippines: 'Filipinas',
  Poland: 'Polonia',
  Portugal: 'Portugal',
  'Puerto Rico': 'Puerto Rico',
  Qatar: 'Catar',
  'Republic of Korea': 'Corea del Sur',
  'Republic of the Congo': 'República del Congo',
  Romania: 'Rumanía',
  Russia: 'Rusia',
  Rwanda: 'Ruanda',
  'Saudi Arabia': 'Arabia Saudita',
  Senegal: 'Senegal',
  Serbia: 'Serbia',
  'Sierra Leone': 'Sierra Leona',
  Slovakia: 'Eslovaquia',
  Slovenia: 'Eslovenia',
  'Solomon Islands': 'Islas Salomón',
  Somalia: 'Somalia',
  Somaliland: 'Somalilandia',
  'South Africa': 'Sudáfrica',
  'South Sudan': 'Sudán del Sur',
  Spain: 'España',
  'Sri Lanka': 'Sri Lanka',
  Sudan: 'Sudán',
  Suriname: 'Surinam',
  Sweden: 'Suecia',
  Switzerland: 'Suiza',
  Syria: 'Siria',
  Taiwan: 'Taiwán',
  Tajikistan: 'Tayikistán',
  Tanzania: 'Tanzania',
  Thailand: 'Tailandia',
  'The Gambia': 'Gambia',
  'Timor-Leste': 'Timor Oriental',
  Togo: 'Togo',
  'Trinidad and Tobago': 'Trinidad y Tobago',
  Tunisia: 'Túnez',
  Turkey: 'Turquía',
  Turkmenistan: 'Turkmenistán',
  Uganda: 'Uganda',
  Ukraine: 'Ucrania',
  'United Arab Emirates': 'Emiratos Árabes Unidos',
  'United Kingdom': 'Reino Unido',
  'United States': 'Estados Unidos',
  Uruguay: 'Uruguay',
  Uzbekistan: 'Uzbekistán',
  Vanuatu: 'Vanuatu',
  Venezuela: 'Venezuela',
  Vietnam: 'Vietnam',
  'Western Sahara': 'Sáhara Occidental',
  Yemen: 'Yemen',
  Zambia: 'Zambia',
  Zimbabwe: 'Zimbabue'
};

// Devuelve la clave de región de regionData.js para un nombre de país del mapa,
// o null si el país no tiene textos en el archivo.
export const normalizeCountryName = (name) => {
  if (!name) return null;
  const key = String(name).trim().toLowerCase();
  return COUNTRY_NAME_TO_REGION[key] || null;
};

// Devuelve el nombre del país en español (para el tooltip del mapa).
// Si no está en el diccionario, devuelve el nombre original.
export const translateCountryName = (name) => {
  if (!name) return name;
  return COUNTRY_EN_TO_ES[name] || name;
};

